pipeline {
    agent { node { label 'AGENT-1' } }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Init') {
            steps {
                echo "for testing purpose"
                // sh'''
                //     cd 01-vpc
                //     ls -lrt
                //     pwd
                //     terraform init
                // '''
            }
        }
        // stage('Plan') {
        //     steps {
        //         sh'''
        //             cd 01-vpc
        //             ls -lrt
        //             pwd
        //             terraform plan
        //         '''
        //     }
        // }
        
    }

    post { 
        always { 
            echo 'I will always run whether job is success or not'
        }
        success{
            echo 'I will run only when job is success'
        }
        failure{
            echo 'I will run when failure'
        }
    }
}